"""initial traas schema

Revision ID: 2f1112c5c11f
Revises: 
Create Date: 2026-06-14 17:36:36.714066
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f1112c5c11f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hazards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hazard_id', sa.String(length=50), nullable=False),
    sa.Column('hazard_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('radius_km', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hazards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hazards_hazard_id'), ['hazard_id'], unique=True)

    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.JSON(), nullable=True),
    sa.Column('destination', sa.JSON(), nullable=True),
    sa.Column('route_type', sa.String(length=30), nullable=True),
    sa.Column('path', sa.JSON(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('duration_min', sa.Float(), nullable=True),
    sa.Column('hazards', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routes_route_id'), ['route_id'], unique=True)

    op.create_table('transport_constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.String(length=50), nullable=True),
    sa.Column('vehicle_type', sa.String(length=30), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transport_constraints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transport_constraints_farm_id'), ['farm_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_constraints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transport_constraints_farm_id'))

    op.drop_table('transport_constraints')
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routes_route_id'))

    op.drop_table('routes')
    with op.batch_alter_table('hazards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hazards_hazard_id'))

    op.drop_table('hazards')
    # ### end Alembic commands ###
