"""initial wfaas schema

Revision ID: 709b3114ae14
Revises: 
Create Date: 2026-06-14 17:36:36.225156
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709b3114ae14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.String(length=50), nullable=True),
    sa.Column('alert_types', sa.JSON(), nullable=True),
    sa.Column('notification_frequency', sa.String(length=20), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_preferences_farm_id'), ['farm_id'], unique=True)

    op.create_table('drone_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.String(length=50), nullable=False),
    sa.Column('farm_id', sa.String(length=50), nullable=True),
    sa.Column('drone_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('mission_type', sa.String(length=50), nullable=True),
    sa.Column('waypoints', sa.JSON(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drone_missions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drone_missions_drone_id'), ['drone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drone_missions_farm_id'), ['farm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drone_missions_mission_id'), ['mission_id'], unique=True)

    op.create_table('drones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('assigned_farm', sa.String(length=50), nullable=True),
    sa.Column('last_maintenance', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drones_drone_id'), ['drone_id'], unique=True)

    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('owner_email', sa.String(length=120), nullable=True),
    sa.Column('drone_fleet', sa.JSON(), nullable=True),
    sa.Column('monitoring_schedule', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farms_farm_id'), ['farm_id'], unique=True)

    op.create_table('weather_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.String(length=50), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('related_data', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_alerts_farm_id'), ['farm_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_alerts_farm_id'))

    op.drop_table('weather_alerts')
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farms_farm_id'))

    op.drop_table('farms')
    with op.batch_alter_table('drones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drones_drone_id'))

    op.drop_table('drones')
    with op.batch_alter_table('drone_missions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drone_missions_mission_id'))
        batch_op.drop_index(batch_op.f('ix_drone_missions_farm_id'))
        batch_op.drop_index(batch_op.f('ix_drone_missions_drone_id'))

    op.drop_table('drone_missions')
    with op.batch_alter_table('alert_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_preferences_farm_id'))

    op.drop_table('alert_preferences')
    # ### end Alembic commands ###
