"""party onboarding roles and role requirements

Revision ID: 3e8d3a6b1c32
Revises: 6f878b19ba1c
Create Date: 2026-06-14 21:00:31.476364
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8d3a6b1c32'
down_revision = '6f878b19ba1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('party_type', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('owner_id', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.Column('region_code', sa.String(length=8), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('compliance_status', sa.String(length=16), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_band', sa.String(length=12), nullable=True),
    sa.Column('suspended_reason', sa.String(length=300), nullable=True),
    sa.Column('screening_status', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parties_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_party_id'), ['party_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_parties_party_type'), ['party_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_parties_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('role_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_code', sa.String(length=8), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('required_docs', sa.JSON(), nullable=True),
    sa.Column('required_screening', sa.Boolean(), nullable=True),
    sa.Column('min_experience_years', sa.Float(), nullable=True),
    sa.Column('needs_accreditation', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_requirements_region_code'), ['region_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_requirements_role'), ['role'], unique=False)

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('risk_band', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('suspended_reason', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('screening_status', sa.String(length=40), nullable=True))

    with op.batch_alter_table('region_compliance_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('require_driver_screening', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('region_compliance_rules', schema=None) as batch_op:
        batch_op.drop_column('require_driver_screening')

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('screening_status')
        batch_op.drop_column('suspended_reason')
        batch_op.drop_column('risk_band')
        batch_op.drop_column('risk_score')

    with op.batch_alter_table('role_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_requirements_role'))
        batch_op.drop_index(batch_op.f('ix_role_requirements_region_code'))

    op.drop_table('role_requirements')
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parties_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_parties_party_type'))
        batch_op.drop_index(batch_op.f('ix_parties_party_id'))
        batch_op.drop_index(batch_op.f('ix_parties_owner_id'))

    op.drop_table('parties')
    # ### end Alembic commands ###
