"""add compliance onboarding and load planning

Revision ID: b804b8bcfb4c
Revises: b516175eabf9
Create Date: 2026-06-14 19:35:38.087737
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b804b8bcfb4c'
down_revision = 'b516175eabf9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approved_agencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('agency_type', sa.String(length=20), nullable=True),
    sa.Column('region_code', sa.String(length=8), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approved_agencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approved_agencies_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_approved_agencies_region_code'), ['region_code'], unique=False)

    op.create_table('compliance_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=True),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('auto', sa.Boolean(), nullable=True),
    sa.Column('decided_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_decisions_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_decisions_entity_type'), ['entity_type'], unique=False)

    op.create_table('compliance_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=True),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('doc_type', sa.String(length=40), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('issuer_code', sa.String(length=50), nullable=True),
    sa.Column('issued_on', sa.String(length=10), nullable=True),
    sa.Column('expiry_on', sa.String(length=10), nullable=True),
    sa.Column('insured_value', sa.Float(), nullable=True),
    sa.Column('coverage', sa.JSON(), nullable=True),
    sa.Column('doc_hash', sa.String(length=80), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_documents_doc_hash'), ['doc_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_documents_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_documents_entity_type'), ['entity_type'], unique=False)

    op.create_table('consolidations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consolidation_id', sa.String(length=50), nullable=False),
    sa.Column('origin_region', sa.String(length=8), nullable=True),
    sa.Column('destination_region', sa.String(length=8), nullable=True),
    sa.Column('load_refs', sa.JSON(), nullable=True),
    sa.Column('total_weight_kg', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consolidations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consolidations_consolidation_id'), ['consolidation_id'], unique=True)

    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('owner_id', sa.String(length=50), nullable=True),
    sa.Column('region_code', sa.String(length=8), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('compliance_status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drivers_driver_id'), ['driver_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_drivers_owner_id'), ['owner_id'], unique=False)

    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=50), nullable=True),
    sa.Column('center_id', sa.String(length=50), nullable=True),
    sa.Column('performed_on', sa.String(length=10), nullable=True),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('valid_until', sa.String(length=10), nullable=True),
    sa.Column('report_ref', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspections_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('region_compliance_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_code', sa.String(length=8), nullable=False),
    sa.Column('required_driver_docs', sa.JSON(), nullable=True),
    sa.Column('required_vehicle_docs', sa.JSON(), nullable=True),
    sa.Column('min_experience_years', sa.Float(), nullable=True),
    sa.Column('min_insured_value', sa.Float(), nullable=True),
    sa.Column('inspection_interval_days', sa.Integer(), nullable=True),
    sa.Column('require_tracker', sa.Boolean(), nullable=True),
    sa.Column('require_onboard_camera', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('region_compliance_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_region_compliance_rules_region_code'), ['region_code'], unique=True)

    op.create_table('service_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('owner_id', sa.String(length=50), nullable=True),
    sa.Column('region_code', sa.String(length=8), nullable=True),
    sa.Column('compliance_status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_centers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_centers_center_id'), ['center_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_centers_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('loads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('load_mode', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('scope', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('origin_region', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('destination_region', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('consolidation_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('insurance_opted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('insurance_level', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('insurance_value', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_loads_consolidation_id'), ['consolidation_id'], unique=False)

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_code', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('driver_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('compliance_status', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('tracker_serial', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('tracker_model', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('tracker_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tracker_serviceable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('camera_serial', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('inspection_valid_until', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_vehicles_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_region_code'), ['region_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_region_code'))
        batch_op.drop_index(batch_op.f('ix_vehicles_driver_id'))
        batch_op.drop_column('inspection_valid_until')
        batch_op.drop_column('camera_serial')
        batch_op.drop_column('tracker_serviceable')
        batch_op.drop_column('tracker_approved')
        batch_op.drop_column('tracker_model')
        batch_op.drop_column('tracker_serial')
        batch_op.drop_column('compliance_status')
        batch_op.drop_column('driver_id')
        batch_op.drop_column('region_code')

    with op.batch_alter_table('loads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loads_consolidation_id'))
        batch_op.drop_column('insurance_value')
        batch_op.drop_column('insurance_level')
        batch_op.drop_column('insurance_opted')
        batch_op.drop_column('consolidation_id')
        batch_op.drop_column('destination_region')
        batch_op.drop_column('origin_region')
        batch_op.drop_column('scope')
        batch_op.drop_column('load_mode')

    with op.batch_alter_table('service_centers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_centers_owner_id'))
        batch_op.drop_index(batch_op.f('ix_service_centers_center_id'))

    op.drop_table('service_centers')
    with op.batch_alter_table('region_compliance_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_region_compliance_rules_region_code'))

    op.drop_table('region_compliance_rules')
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspections_vehicle_id'))

    op.drop_table('inspections')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_owner_id'))
        batch_op.drop_index(batch_op.f('ix_drivers_driver_id'))

    op.drop_table('drivers')
    with op.batch_alter_table('consolidations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consolidations_consolidation_id'))

    op.drop_table('consolidations')
    with op.batch_alter_table('compliance_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_documents_entity_type'))
        batch_op.drop_index(batch_op.f('ix_compliance_documents_entity_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_documents_doc_hash'))

    op.drop_table('compliance_documents')
    with op.batch_alter_table('compliance_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_decisions_entity_type'))
        batch_op.drop_index(batch_op.f('ix_compliance_decisions_entity_id'))

    op.drop_table('compliance_decisions')
    with op.batch_alter_table('approved_agencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approved_agencies_region_code'))
        batch_op.drop_index(batch_op.f('ix_approved_agencies_code'))

    op.drop_table('approved_agencies')
    # ### end Alembic commands ###
