"""add shipment route_factor

Revision ID: b516175eabf9
Revises: c97b1a9b2c0b
Create Date: 2026-06-14 19:10:47.247296
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b516175eabf9'
down_revision = 'c97b1a9b2c0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_factor', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_column('route_factor')

    # ### end Alembic commands ###
