"""initial lgaas schema

Revision ID: be501c1513d3
Revises: 
Create Date: 2026-06-14 17:43:28.374593
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be501c1513d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=50), nullable=False),
    sa.Column('shipper_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('origin', sa.JSON(), nullable=True),
    sa.Column('destination', sa.JSON(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('dimensions_cm', sa.JSON(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('load_type', sa.String(length=40), nullable=True),
    sa.Column('classifications', sa.JSON(), nullable=True),
    sa.Column('pickup_window', sa.JSON(), nullable=True),
    sa.Column('delivery_deadline', sa.String(length=40), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('awarded_offer_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loads_ref'), ['ref'], unique=True)
        batch_op.create_index(batch_op.f('ix_loads_shipper_id'), ['shipper_id'], unique=False)

    op.create_table('negotiation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('load_ref', sa.String(length=50), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.String(length=50), nullable=True),
    sa.Column('author_role', sa.String(length=30), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('body', sa.String(length=2000), nullable=True),
    sa.Column('negotiation_style', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('negotiation_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_negotiation_messages_load_ref'), ['load_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_negotiation_messages_offer_id'), ['offer_id'], unique=False)

    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('load_ref', sa.String(length=50), nullable=True),
    sa.Column('bidder_id', sa.String(length=50), nullable=True),
    sa.Column('bidder_role', sa.String(length=30), nullable=True),
    sa.Column('vehicle_id', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('eta_hours', sa.Float(), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('negotiation_style', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_bidder_id'), ['bidder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_load_ref'), ['load_ref'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.String(length=50), nullable=True),
    sa.Column('vehicle_type', sa.String(length=40), nullable=True),
    sa.Column('capacity_kg', sa.Float(), nullable=True),
    sa.Column('capacity_m3', sa.Float(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('base_rate_per_km', sa.Float(), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('available', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_vehicle_id'), ['vehicle_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicles_owner_id'))

    op.drop_table('vehicles')
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_load_ref'))
        batch_op.drop_index(batch_op.f('ix_offers_bidder_id'))

    op.drop_table('offers')
    with op.batch_alter_table('negotiation_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_negotiation_messages_offer_id'))
        batch_op.drop_index(batch_op.f('ix_negotiation_messages_load_ref'))

    op.drop_table('negotiation_messages')
    with op.batch_alter_table('loads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loads_shipper_id'))
        batch_op.drop_index(batch_op.f('ix_loads_ref'))

    op.drop_table('loads')
    # ### end Alembic commands ###
