"""add holidays

Revision ID: 1342f2467131
Revises: 718362fd9191
Create Date: 2026-06-14 18:41:58.091095
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1342f2467131'
down_revision = '718362fd9191'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('region_code', sa.String(length=8), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('recurrence', sa.String(length=10), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holidays_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_holidays_region_code'), ['region_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holidays_region_code'))
        batch_op.drop_index(batch_op.f('ix_holidays_code'))

    op.drop_table('holidays')
    # ### end Alembic commands ###
