"""service center workflow and full tenant columns

Revision ID: 6f878b19ba1c
Revises: ceaa3dcd6ae2
Create Date: 2026-06-14 20:44:59.735994
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f878b19ba1c'
down_revision = 'ceaa3dcd6ae2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliance_decisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_compliance_decisions_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('compliance_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_compliance_documents_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_inspections_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_insurance_claims_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_insurance_policies_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('kyc_checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_kyc_checks_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('proofs_of_delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_proofs_of_delivery_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_ratings_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('region_compliance_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_service_center_docs', sa.JSON(), nullable=True))

    with op.batch_alter_table('service_centers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_reg_no', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('risk_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('risk_band', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('suspended_reason', sa.String(length=300), nullable=True))

    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_settlements_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlements_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('service_centers', schema=None) as batch_op:
        batch_op.drop_column('suspended_reason')
        batch_op.drop_column('risk_band')
        batch_op.drop_column('risk_score')
        batch_op.drop_column('business_reg_no')

    with op.batch_alter_table('region_compliance_rules', schema=None) as batch_op:
        batch_op.drop_column('required_service_center_docs')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('proofs_of_delivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proofs_of_delivery_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('kyc_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kyc_checks_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurance_policies_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurance_claims_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspections_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('compliance_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_documents_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('compliance_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_decisions_tenant_id'))
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
