"""add tax_rules

Revision ID: 718362fd9191
Revises: be501c1513d3
Create Date: 2026-06-14 18:19:28.117974
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718362fd9191'
down_revision = 'be501c1513d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('region_code', sa.String(length=8), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('tax_type', sa.String(length=30), nullable=True),
    sa.Column('collection', sa.String(length=12), nullable=True),
    sa.Column('rate_percent', sa.Float(), nullable=True),
    sa.Column('basis', sa.String(length=12), nullable=True),
    sa.Column('applies_to', sa.JSON(), nullable=True),
    sa.Column('threshold_min', sa.Float(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.String(length=10), nullable=True),
    sa.Column('effective_to', sa.String(length=10), nullable=True),
    sa.Column('statutory_reference', sa.String(length=300), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_rules_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_tax_rules_region_code'), ['region_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_rules_region_code'))
        batch_op.drop_index(batch_op.f('ix_tax_rules_code'))

    op.drop_table('tax_rules')
    # ### end Alembic commands ###
