"""add shipment tracking

Revision ID: c97b1a9b2c0b
Revises: 1342f2467131
Create Date: 2026-06-14 18:51:04.797509
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c97b1a9b2c0b'
down_revision = '1342f2467131'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delay_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delay_reasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delay_reasons_code'), ['code'], unique=True)

    op.create_table('shipment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reason_code', sa.String(length=40), nullable=True),
    sa.Column('reason_label', sa.String(length=160), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('delay_minutes', sa.Float(), nullable=True),
    sa.Column('eta', sa.String(length=40), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_events_shipment_id'), ['shipment_id'], unique=False)

    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.String(length=50), nullable=False),
    sa.Column('load_ref', sa.String(length=50), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('carrier_id', sa.String(length=50), nullable=True),
    sa.Column('vehicle_id', sa.String(length=50), nullable=True),
    sa.Column('driver_name', sa.String(length=120), nullable=True),
    sa.Column('driver_phone', sa.String(length=40), nullable=True),
    sa.Column('region_code', sa.String(length=8), nullable=True),
    sa.Column('origin', sa.JSON(), nullable=True),
    sa.Column('destination', sa.JSON(), nullable=True),
    sa.Column('current_location', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('planned_distance_km', sa.Float(), nullable=True),
    sa.Column('avg_speed_kmh', sa.Float(), nullable=True),
    sa.Column('delay_minutes', sa.Float(), nullable=True),
    sa.Column('eta', sa.String(length=40), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('last_update_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipments_load_ref'), ['load_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_shipment_id'), ['shipment_id'], unique=True)

    op.create_table('track_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.String(length=50), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('track_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_points_shipment_id'), ['shipment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_points_shipment_id'))

    op.drop_table('track_points')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_load_ref'))

    op.drop_table('shipments')
    with op.batch_alter_table('shipment_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_events_shipment_id'))

    op.drop_table('shipment_events')
    with op.batch_alter_table('delay_reasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delay_reasons_code'))

    op.drop_table('delay_reasons')
    # ### end Alembic commands ###
