"""add platform enhancements reputation telematics payments insurance

Revision ID: 251a509d1122
Revises: b804b8bcfb4c
Create Date: 2026-06-14 19:59:08.417418
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251a509d1122'
down_revision = 'b804b8bcfb4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=300), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duty_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('duty_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duty_logs_driver_id'), ['driver_id'], unique=False)

    op.create_table('escrows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escrow_id', sa.String(length=50), nullable=False),
    sa.Column('shipment_id', sa.String(length=50), nullable=True),
    sa.Column('load_ref', sa.String(length=50), nullable=True),
    sa.Column('payer_id', sa.String(length=50), nullable=True),
    sa.Column('payee_id', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escrows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escrows_escrow_id'), ['escrow_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_escrows_shipment_id'), ['shipment_id'], unique=False)

    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=300), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_records_key'), ['key'], unique=True)

    op.create_table('insurance_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.String(length=50), nullable=False),
    sa.Column('policy_id', sa.String(length=50), nullable=True),
    sa.Column('shipment_id', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insurance_claims_claim_id'), ['claim_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_insurance_claims_policy_id'), ['policy_id'], unique=False)

    op.create_table('insurance_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.String(length=50), nullable=False),
    sa.Column('load_ref', sa.String(length=50), nullable=True),
    sa.Column('shipment_id', sa.String(length=50), nullable=True),
    sa.Column('insurer_code', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=True),
    sa.Column('sum_insured', sa.Float(), nullable=True),
    sa.Column('premium', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insurance_policies_load_ref'), ['load_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurance_policies_policy_id'), ['policy_id'], unique=True)

    op.create_table('insurance_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('insurer_code', sa.String(length=50), nullable=True),
    sa.Column('region_code', sa.String(length=8), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=True),
    sa.Column('rate_percent', sa.Float(), nullable=True),
    sa.Column('min_premium', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurance_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insurance_rates_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_insurance_rates_region_code'), ['region_code'], unique=False)

    op.create_table('proofs_of_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.String(length=50), nullable=True),
    sa.Column('recipient_name', sa.String(length=120), nullable=True),
    sa.Column('signature_ref', sa.String(length=200), nullable=True),
    sa.Column('photo_refs', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('delivered_at', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proofs_of_delivery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proofs_of_delivery_shipment_id'), ['shipment_id'], unique=False)

    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=True),
    sa.Column('subject_id', sa.String(length=50), nullable=True),
    sa.Column('rater_id', sa.String(length=50), nullable=True),
    sa.Column('shipment_id', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratings_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_subject_type'), ['subject_type'], unique=False)

    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escrow_id', sa.String(length=50), nullable=True),
    sa.Column('gross', sa.Float(), nullable=True),
    sa.Column('tax_total', sa.Float(), nullable=True),
    sa.Column('withheld', sa.Float(), nullable=True),
    sa.Column('net_to_payee', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlements_escrow_id'), ['escrow_id'], unique=False)

    op.create_table('telematics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=24), nullable=True),
    sa.Column('severity', sa.String(length=12), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telematics_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telematics_events_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('telematics_pings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=50), nullable=True),
    sa.Column('shipment_id', sa.String(length=50), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('odometer_km', sa.Float(), nullable=True),
    sa.Column('fuel_level', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telematics_pings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telematics_pings_vehicle_id'), ['vehicle_id'], unique=False)

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telematics_status', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('odometer_km', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('odometer_km')
        batch_op.drop_column('last_heartbeat_at')
        batch_op.drop_column('telematics_status')

    with op.batch_alter_table('telematics_pings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telematics_pings_vehicle_id'))

    op.drop_table('telematics_pings')
    with op.batch_alter_table('telematics_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telematics_events_vehicle_id'))

    op.drop_table('telematics_events')
    with op.batch_alter_table('settlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlements_escrow_id'))

    op.drop_table('settlements')
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_subject_type'))
        batch_op.drop_index(batch_op.f('ix_ratings_subject_id'))

    op.drop_table('ratings')
    with op.batch_alter_table('proofs_of_delivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proofs_of_delivery_shipment_id'))

    op.drop_table('proofs_of_delivery')
    with op.batch_alter_table('insurance_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurance_rates_region_code'))
        batch_op.drop_index(batch_op.f('ix_insurance_rates_code'))

    op.drop_table('insurance_rates')
    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurance_policies_policy_id'))
        batch_op.drop_index(batch_op.f('ix_insurance_policies_load_ref'))

    op.drop_table('insurance_policies')
    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurance_claims_policy_id'))
        batch_op.drop_index(batch_op.f('ix_insurance_claims_claim_id'))

    op.drop_table('insurance_claims')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_records_key'))

    op.drop_table('idempotency_records')
    with op.batch_alter_table('escrows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escrows_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_escrows_escrow_id'))

    op.drop_table('escrows')
    with op.batch_alter_table('duty_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duty_logs_driver_id'))

    op.drop_table('duty_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
