"""add tenant columns and kyc checks

Revision ID: ceaa3dcd6ae2
Revises: 251a509d1122
Create Date: 2026-06-14 20:34:34.164942
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceaa3dcd6ae2'
down_revision = '251a509d1122'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=True),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kyc_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kyc_checks_document_id'), ['document_id'], unique=False)

    with op.batch_alter_table('consolidations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_consolidations_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_drivers_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('escrows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_escrows_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('loads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_loads_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_offers_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('service_centers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_service_centers_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_shipments_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_vehicles_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('service_centers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_centers_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('loads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loads_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('escrows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escrows_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('consolidations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consolidations_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('kyc_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kyc_checks_document_id'))

    op.drop_table('kyc_checks')
    # ### end Alembic commands ###
